backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/home.json"
        label: "Conteúdo"
        name: "home"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Subtítulo", name: "subtitulo", widget: "text" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Imagem (opcional)", name: "imagem", widget: "image", required: false }
